image: node:latest

# Pipeline
stages:
  - install
  - build
  - test

variables:
   npm_config_cache: "$CI_PROJECT_DIR/.npm"
   CYPRESS_CACHE_FOLDER: "$CI_PROJECT_DIR/cache/Cypress"

cache:
   key:
     files:
        - cd movies
        - package.json
   paths:
      - .npm
      - cache/Cypress
      - movies/node_modules

# Jobs 
# Jobs 
install_dependencies:
  stage: install
  script:
    - cd movies
    - npm ci --cache .npm --prefer-offline

bundle_app:
  stage: build
  script:
    - cd movies
    - npm run build